### ISSUE TITLE
Crash on using manasteel hammer

### ISSUE THREAD

**Issue by lamoyrl90** [Partonetrain/managear#1]
MC 1.15.2
Mana Gear 1.1
Silent Gear 1.6.1 87

latest.log [relevant section]: https://pastebin.com/sfjx9g8M

Happened on the first block breaking event using my hammer. I can't re-enter my world now.

**Comment by Partonetrain** [comment]
I'm really sorry about your world. I will fix this as soon as I can.

**Comment by lamoyrl90** [comment]
I actually was able to get back in when I disabled the mod, so no damage done

**Comment by Partonetrain** [comment]
My workspace had a pretty ancient Botania API version, should be fixed in 1.1.1. Sorry for the trouble. Let me know if it works for you.

**Comment by lamoyrl90** [comment]
Works like a charm *thumbs up*
