### ISSUE TITLE
[1.15.2] Mana Gear Parts Invisible

### ISSUE THREAD

**Issue by MokahTGS** [Partonetrain/managear#3]
So making marts with the mana trait from mana steel makes the parts invisible.  The parts are there, they work, are repaired with mana like they should be, just are missing their textures.  If the tools have diamond tips you can see them...just not the rest of the tool part.

https://www.dropbox.com/s/0rrteiyszpqeptx/2020-07-31_14.02.32.png?dl=0

SilentGear-1.15.2-1.11.0+147
managear-1.1.1

**Comment by MokahTGS** [comment]
Actually....looking at the tools now they don't seem to be healing with mana yet mana is draining out of tablets and my ring of mana.

**Comment by Partonetrain** [comment]
If I had to guess, the first thing is probably the fault of the new SGear Material Adapters, I'll ask Silent. Second issue is #2.

Edit: Sgear changed its model system in 1.11.0. Going to fix on my end.
