### ISSUE TITLE
Latest Silent Gear update requires this mod to update

### ISSUE THREAD

**Issue by superninjakiwi** [Partonetrain/managear#5]
Just thought I'd drop in and let you know, with the most recent update to Silent Gear, it looks like the net/silentchaos512/gear/traits/SimpleTrait$Serializer class can't be found, which means the game can't start up with managear installed.

**Comment by SDUBZ** [comment]
getting crash on load up too 
managear-1.16.1-2.0.1.jar
SilentGear-1.16.1-2.1.0+161
forge:1.16.1-32.0.108

[latest.log](https://github.com/Partonetrain/managear/files/5090384/latest.log)
@Partonetrain

**Comment by Partonetrain** [comment]
Yup, I was warned by Silent. Should be easy to fix. Should be able to get around to it tomorrow.

**Comment by Partonetrain** [comment]
I wasn't actually able to reproduce this. The class in SGear is still there, just marked as deprecated, don't understand why this would be happening to others. Either way, uploading ManaGear 2.1.0 to Curse now and I'm confident that will fix it

**Comment by superninjakiwi** [comment]
I'm not sure what the difference in environments was, but 2.1.0 does indeed fix it. Thanks for fixing it so quickly!
