### ISSUE TITLE
Mana Tablet gets drained completely if tool not held

### ISSUE THREAD

**Issue by GarthF** [Partonetrain/managear#7]
## Versions

- **Mana Gear**: 1.16.3-2.1.2
- **Silent Gear**: 1.16.3-2.3.2
- **Silent Lib**: 1.16.3-4.8.1
- **Forge**: 34.1.25
- **Modpack**: TNP Limitless 3
- **Optifine Installed**: No 

## Expected Behavior
On picking up a mana tablet, any tool with damage should be repaired, mana use should cease once all repairs done.

## Actual Behavior
If a damaged tool is not held, mana drains from the tablet constantly, but no repair happens. Switching to the tool causes the repair to start, but it only takes one damaged tool in inventory to drain the tablet completely.

## Steps to Reproduce the Problem

1. Create a tool (I used a bow, paxel or shears) with the mana 1 trait
2. Drop your mana tablet into the mana pool to charge up.
3. Use the tool to damage it, switch away from the tool to another toolslot
4. Pick up the mana tablet. The tool does not repair and the tablet drains constantly.

**Comment by Partonetrain** [comment]
Confirmed, and I know why this happens - it's a stupid mistake on my part. I bet this is the case in 1.15 too... 
So sorry about that, Uploading a fix to CurseForge now.

**Comment by Partonetrain** [comment]
Actually keeping this open in case someone is still using 1.15 and wants to request that I fix it (don't have time right now as small of a task as it is)

**Comment by Partonetrain** [comment]
1.15 is no longer supported
